# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3c030f3c-3959-48d6-b6a7-bf2e97521124";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c85cfb8a-6b23-4c0b-8250-714571c78631".device = "/dev/disk/by-uuid/c85cfb8a-6b23-4c0b-8250-714571c78631";

  fileSystems."/mnt/ciberia" =
    { device = "/dev/disk/by-uuid/fb7f61ed-7d32-46d8-a49c-3e827a25af93";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."ciberia".device = "/dev/disk/by-uuid/3d605ccd-16d4-4b1f-ad18-11d71cbd9c3e";

  fileSystems."/mnt/flame" =
    { device = "/dev/disk/by-uuid/7fb8b134-5992-42e1-b136-7d1088fd10fd";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."flame".device = "/dev/disk/by-uuid/d0e627bb-98c3-439b-adf0-d114ca98befa";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DEBE-1F6A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.virbr0.useDHCP = lib.mkDefault true;
  # networking.interfaces.vnet1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
